spring.application.name=EduTrack

# DATABASE CONNECTION (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/edutrack
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
